import { useState, type ReactNode } from 'react';

type CharterVessel = { id: string; name: string; type: string; dwt: string; year: string; rate: number; availability: string; tone: string };

const vessels: CharterVessel[] = [
  { id: 'ocean-pride', name: 'MV Ocean Pride', type: 'Panamax', dwt: '82,341', year: '2019', rate: 16400, availability: 'Available', tone: 'text-emerald-600' },
  { id: 'eastern-star', name: 'Eastern Star', type: 'Panamax', dwt: '81,200', year: '2021', rate: 17100, availability: 'Available', tone: 'text-emerald-600' },
  { id: 'sea-voyager', name: 'Sea Voyager', type: 'Panamax', dwt: '78,900', year: '2018', rate: 16800, availability: 'In 5 days', tone: 'text-amber-600' },
];

function shipThumb(size = 'h-8 w-9') {
  return <span className={`grid ${size} place-items-center rounded bg-[linear-gradient(145deg,#c9e1ed,#386a85)] text-sm shadow-inner`}>⚓</span>;
}

export function PlanCharterPage() {
  const [cargo, setCargo] = useState('Coal');
  const [quantity, setQuantity] = useState(100000);
  const [origin, setOrigin] = useState('Hay Point (AUS)');
  const [destination, setDestination] = useState('Paradip (IND)');
  const [vesselClass, setVesselClass] = useState('Panamax');
  const [selectedId, setSelectedId] = useState(vessels[0].id);
  const [vesselTab, setVesselTab] = useState('Best Match (3)');
  const [draftSaved, setDraftSaved] = useState(false);
  const [ready, setReady] = useState(false);
  const selected = vessels.find((vessel) => vessel.id === selectedId) ?? vessels[0];
  const freightCost = selected.rate * 20;
  const totalCost = freightCost + 315000 + 520000 + 45000;

  return <section className="space-y-3 text-[#17345d]">
    <div className="flex flex-col justify-between gap-4 xl:flex-row xl:items-end"><div><p className="text-[11px] font-bold tracking-[.25em] text-[#617a96]">CHARTER PLANNING</p><h1 className="mt-1 text-3xl font-extrabold tracking-tight text-[#12396e] sm:text-4xl">Plan Charter</h1><p className="mt-1 text-base text-[#55708e]">Configure your cargo, route and requirements to find the best chartering options.</p></div><div className="flex gap-3"><button className={`rounded-md border px-4 py-3 text-xs font-bold shadow-sm ${draftSaved ? 'border-emerald-200 bg-emerald-50 text-emerald-700' : 'border-[#d5e4ee] bg-white text-[#24527c] hover:bg-[#f5fbff]'}`} onClick={() => setDraftSaved(true)} type="button">▣ {draftSaved ? 'Draft Saved' : 'Save as Draft'}</button><button className="rounded-md bg-[#104f97] px-5 py-3 text-xs font-bold text-white shadow-sm hover:bg-[#0b4381]" onClick={() => setReady(true)} type="button">Proceed to Contract →</button></div></div>
    {ready ? <div className="rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800"><b>Ready to proceed:</b> the selected vessel and cost estimate are confirmed for this prototype plan.</div> : null}
    <div className="grid grid-cols-4 rounded-xl border border-[#dceaf2] bg-white px-3 py-3 shadow-sm">{[['1', 'Cargo & Route', 'Define your requirements'], ['2', 'Vessel Selection', 'View recommended vessels'], ['3', 'Voyage & Economics', 'Compare costs and timelines'], ['4', 'Review & Proceed', 'Confirm and create contract']].map(([number, label, detail], index) => <div className="relative flex items-center gap-3 px-1 sm:px-3" key={number}><span className={`grid h-9 w-9 shrink-0 place-items-center rounded-full text-sm font-extrabold ${index === 0 ? 'bg-[#104e91] text-white shadow-md' : 'bg-[#dcebf6] text-[#25537f]'}`}>{number}</span><span className="hidden lg:block"><b className="block text-xs text-[#1e426f]">{label}</b><small className="text-[10px] text-[#617b96]">{detail}</small></span>{index < 3 ? <span className="absolute -right-1 text-2xl font-light text-[#d6e2eb]">›</span> : null}</div>)}</div>
    <form className="grid gap-3 rounded-xl border border-[#dceaf2] bg-white p-3 shadow-sm xl:grid-cols-[1fr_.8fr_1.05fr_1.05fr_1fr_.95fr_auto]" onSubmit={(event) => { event.preventDefault(); setReady(false); }}><CharterField label="Cargo Type"><select onChange={(event) => setCargo(event.target.value)} value={cargo}><option>Coal</option><option>Iron Ore</option><option>Pet Coke</option></select></CharterField><CharterField label="Quantity (MT)"><input min="1000" onChange={(event) => setQuantity(Number(event.target.value))} type="number" value={quantity} /></CharterField><CharterField label="Origin Port"><select onChange={(event) => setOrigin(event.target.value)} value={origin}><option>Hay Point (AUS)</option><option>Gladstone (AUS)</option><option>Newcastle (AUS)</option></select></CharterField><CharterField label="Destination Port"><select onChange={(event) => setDestination(event.target.value)} value={destination}><option>Paradip (IND)</option><option>Vizag (IND)</option><option>Gangavaram (IND)</option></select></CharterField><CharterField label="Preferred Vessel Type"><select onChange={(event) => setVesselClass(event.target.value)} value={vesselClass}><option>Panamax</option><option>Supramax</option><option>Capesize</option></select></CharterField><CharterField label="Target Loading Date"><input defaultValue="2026-10-15" type="date" /></CharterField><button className="mt-auto rounded-md bg-[#0873dc] px-6 py-3 text-sm font-bold text-white shadow-sm hover:bg-[#0560b7]" type="submit">Find Best Options →</button></form>
    <div className="grid gap-3 xl:grid-cols-[1.45fr_.85fr_1fr]">
      <div className="space-y-3"><article className="relative min-h-[286px] overflow-hidden rounded-xl border border-[#bddde9] bg-[linear-gradient(145deg,#d8eef4,#74b3c7_48%,#266f94)] shadow-sm"><div className="absolute inset-0 opacity-35" style={{ backgroundImage: 'linear-gradient(rgba(255,255,255,.3) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.3) 1px,transparent 1px)', backgroundSize: '40px 40px' }} /><div className="absolute inset-0 bg-[radial-gradient(ellipse_at_15%_30%,rgba(218,220,180,.85),transparent_25%),radial-gradient(ellipse_at_74%_80%,rgba(218,230,177,.9),transparent_29%)]" /><div className="absolute left-3 top-3 z-10"><h2 className="text-base font-extrabold text-white drop-shadow">Route Overview</h2></div><div className="absolute right-3 top-12 z-10 rounded-lg bg-white/95 p-3 text-[11px] leading-6 text-[#49637f] shadow"><p>Distance <b className="float-right ml-8 text-[#183d68]">4,892 NM</b></p><p>Est. Transit Time <b className="float-right text-[#183d68]">18 – 22 days</b></p><p>Avg. Speed <b className="float-right text-[#183d68]">12.5 knots</b></p></div><svg aria-label="Charter route map placeholder" className="absolute inset-0 h-full w-full" viewBox="0 0 600 290" preserveAspectRatio="none"><path d="M420 185 C355 173 315 168 270 140 S198 91 150 60" fill="none" stroke="#fff" strokeDasharray="9 7" strokeWidth="4" /><path d="M420 185 C355 173 315 168 270 140 S198 91 150 60" fill="none" stroke="#2277ca" strokeDasharray="7 7" strokeWidth="2" />{[[420,185],[345,164],[270,140],[205,92],[150,60]].map(([x,y]) => <circle cx={x} cy={y} fill="#1676cb" key={`${x}-${y}`} r="5" stroke="white" strokeWidth="3" />)}</svg><span className="absolute right-[32%] bottom-[31%] text-2xl">🚢</span><p className="absolute bottom-12 left-5 text-xs font-bold text-white drop-shadow">Route-map placeholder · {origin} → {destination}</p><button className="absolute bottom-3 left-3 rounded-md bg-white/95 px-3 py-2 text-xs font-bold text-[#1475c8] shadow" type="button">⌖ View on Map</button></article>
        <article className="rounded-xl border border-[#dceaf2] bg-white p-3 shadow-sm"><div className="flex justify-between"><h2 className="text-base font-extrabold text-[#153a70]">Recommended Vessels</h2><button className="text-xs font-bold text-[#0f75cb]" type="button">View All →</button></div><div className="mt-2 flex rounded-md bg-[#f3f8fc] p-1 text-[10px] font-bold">{['Best Match (3)', 'Also Consider (5)', 'All Available (12)'].map((tab) => <button className={`rounded px-3 py-2 ${vesselTab === tab ? 'bg-[#1479d6] text-white shadow-sm' : 'text-[#5f7891]'}`} key={tab} onClick={() => setVesselTab(tab)} type="button">{tab}</button>)}</div><div className="mt-2 overflow-x-auto"><table className="w-full min-w-[530px] text-left text-[10px]"><thead className="border-y border-[#e4edf3] text-[#6c8298]"><tr>{['#', 'Vessel Name', 'Type', 'DWT', 'Year Built', 'Est. Rate (USD/day)', 'Availability', 'Action'].map((label) => <th className="px-1.5 py-2 font-semibold" key={label}>{label}</th>)}</tr></thead><tbody>{vessels.map((vessel, index) => <tr className={`border-b border-[#edf2f5] ${vessel.id === selectedId ? 'bg-[#f1f8ff]' : ''}`} key={vessel.id}><td className="px-1.5 py-2 text-[#53708d]">{index + 1}</td><td className="px-1.5 py-2"><span className="flex items-center gap-2 font-bold text-[#36557a]">{shipThumb()}{vessel.name}</span></td><td className="px-1.5 py-2 text-[#48637e]">{vessel.type}</td><td className="px-1.5 py-2 text-[#48637e]">{vessel.dwt}</td><td className="px-1.5 py-2 text-[#48637e]">{vessel.year}</td><td className="px-1.5 py-2 text-[#48637e]">{vessel.rate.toLocaleString()}</td><td className={`px-1.5 py-2 font-semibold ${vessel.tone}`}>● {vessel.availability}</td><td className="px-1.5 py-2"><button className={`rounded border px-2.5 py-1 font-bold ${vessel.id === selectedId ? 'border-[#1479d6] bg-[#1479d6] text-white' : 'border-[#8cbde3] text-[#1372c6]'}`} onClick={() => setSelectedId(vessel.id)} type="button">{vessel.id === selectedId ? 'Selected' : 'Select'}</button></td></tr>)}</tbody></table></div></article></div>
      <div className="space-y-3"><article className="rounded-xl border border-[#dceaf2] bg-white p-4 shadow-sm"><h2 className="text-base font-extrabold text-[#153a70]">Route Details</h2><div className="mt-4 grid grid-cols-[24px_1fr_1fr] gap-y-4 text-xs"><span className="text-emerald-500">●</span><div><b className="text-[#284b70]">{origin}</b><small className="mt-1 block text-slate-500">Load Port</small></div><div><small className="text-slate-500">ETD</small><b className="block text-[#284b70]">15 Oct 2026</b></div><span className="text-[#1478d1]">⚓</span><div><b className="text-[#284b70]">En Route</b><small className="mt-1 block text-slate-500">4,892 NM</small></div><div><small className="text-slate-500">Est. Duration</small><b className="block text-[#284b70]">18 – 22 days</b></div><span className="text-rose-500">●</span><div><b className="text-[#284b70]">{destination}</b><small className="mt-1 block text-slate-500">Discharge Port</small></div><div><small className="text-slate-500">ETA</small><b className="block text-[#284b70]">02 – 06 Nov 2026</b></div></div><div className="mt-4 rounded-lg bg-[#f4fbff] p-3 text-[11px] text-[#45627d]"><b className="text-[#163c69]">ⓘ Key Considerations</b><p className="mt-2">✓ Seasonal weather conditions are favorable</p><p>✓ No major port restrictions</p><p>✓ Suitable for {vesselClass} vessels</p></div></article><article className="rounded-xl border border-[#dceaf2] bg-white p-4 shadow-sm"><h2 className="text-base font-extrabold text-[#153a70]">Cost Estimate <span className="text-xs font-normal text-slate-500">(USD)</span></h2><dl className="mt-3 divide-y divide-[#e7eff4] text-xs">{[['Freight Rate', `${selected.rate.toLocaleString()} / day`], ['Est. Voyage Days', '20 days'], ['Freight Cost', freightCost.toLocaleString()], ['Port Charges (Load + Discharge)', '315,000'], ['Bunker (Est.)', '520,000'], ['Other Costs', '45,000']].map(([label, value]) => <div className="flex justify-between py-2" key={label}><dt className="text-[#5f7891]">{label}</dt><dd className="font-semibold text-[#24486f]">{value}</dd></div>)}<div className="flex justify-between bg-[#edf7ff] px-2 py-3 text-sm"><dt className="font-extrabold text-[#173e6b]">Total Estimated Cost</dt><dd className="font-extrabold text-[#173e6b]">{totalCost.toLocaleString()}</dd></div></dl></article></div>
      <aside className="space-y-3"><article className="rounded-xl border border-[#dceaf2] bg-white p-3 shadow-sm"><h2 className="text-base font-extrabold text-[#153a70]">Cargo & Port Information</h2><div className="mt-3 grid grid-cols-2 rounded-md bg-[#f4f9fd] p-1 text-[10px] font-bold"><span className="rounded bg-[#1479d6] px-3 py-2 text-center text-white">Load Port</span><span className="px-3 py-2 text-center text-[#5d7891]">Discharge Port</span></div><PortCard name={origin} draft="16.0 m" rate="8,000 – 10,000 MT/day" wait="1 – 2 days" charge="~ 195,000" /><PortCard name={destination} draft="14.5 m" rate="7,000 – 9,000 MT/day" wait="1 – 3 days" charge="~ 120,000" /></article><article className="rounded-xl border border-[#dceaf2] bg-white p-3 shadow-sm"><h2 className="text-base font-extrabold text-[#153a70]">Timeline Overview</h2><div className="mt-5 flex items-start justify-between text-center text-[10px]"><span className="w-20"><i className="mx-auto block h-3 w-3 rounded-full bg-emerald-500" /><b className="mt-2 block text-[#315274]">15 Oct</b><small className="text-slate-500">Load at Hay Point</small></span><span className="mt-1 h-0.5 flex-1 bg-[#5e9fda]" /><span className="w-20"><i className="mx-auto block h-3 w-3 rounded-full bg-[#1479d6]" /><b className="mt-2 block text-[#315274]">02 Nov</b><small className="text-slate-500">ETA at Paradip</small></span><span className="mt-1 h-0.5 flex-1 bg-[#c5d4e3]" /><span className="w-20"><i className="mx-auto block h-3 w-3 rounded-full bg-[#b9c8d7]" /><b className="mt-2 block text-[#315274]">06 Nov</b><small className="text-slate-500">Discharge Complete</small></span></div></article><article className="rounded-xl border border-emerald-100 bg-[linear-gradient(145deg,#effff7,#fff)] p-4 shadow-sm"><b className="text-[#157351]">▣ Estimated Savings</b><h2 className="mt-1 text-lg font-extrabold text-[#159464]">Up to 12% lower cost</h2><p className="mt-1 text-xs text-[#527468]">vs. market average based on current rates.</p></article></aside>
    </div>
    <div className="grid gap-3 xl:grid-cols-[1fr_1.25fr_310px]"><article className="rounded-xl border border-[#dceaf2] bg-white p-3 shadow-sm xl:col-span-2"><div className="flex gap-2"><h2 className="mr-auto text-base font-extrabold text-[#153a70]">Alternative Options</h2><button className="rounded bg-[#1479d6] px-3 py-1.5 text-[10px] font-bold text-white" type="button">Different Vessel Types</button><button className="rounded bg-[#f3f8fc] px-3 py-1.5 text-[10px] font-bold text-[#607991]" type="button">Alternative Routes</button><button className="rounded bg-[#f3f8fc] px-3 py-1.5 text-[10px] font-bold text-[#607991]" type="button">Different Dates</button></div><div className="mt-3 grid gap-3 md:grid-cols-3"><Alternative title="Supramax Option" vessel="MV Cape Harmony" rate="$14,200 / day" savings="-8%" /><Alternative title="Handysize Option" vessel="MV River Star" rate="$13,100 / day" savings="-12%" /><Alternative title="Later Date Option" vessel="Load on 01 Nov 2026" rate="$15,800 / day" savings="-4%" /></div></article><article className="rounded-xl border border-emerald-100 bg-[linear-gradient(145deg,#effff7,#fff)] p-4 shadow-sm"><div className="flex gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-emerald-100 text-xl text-emerald-600">✓</span><div><b className="text-[#157351]">Ready to Proceed?</b><p className="mt-1 text-xs text-[#527468]">You can now move to contract creation with the selected option.</p></div></div><button className="mt-4 w-full rounded-md bg-[#129d6d] py-3 text-sm font-bold text-white shadow-sm" onClick={() => setReady(true)} type="button">Proceed to Contract →</button></article></div>
  </section>;
}

function CharterField({ label, children }: { label: string; children: ReactNode }) {
  return <label className="text-[11px] font-semibold text-[#58728d]">{label}<span className="mt-1 block [&_input]:w-full [&_input]:rounded-md [&_input]:border [&_input]:border-[#dbe8f0] [&_input]:bg-[#f8fbfd] [&_input]:px-3 [&_input]:py-2 [&_input]:text-xs [&_input]:font-semibold [&_input]:text-[#1e416a] [&_select]:w-full [&_select]:rounded-md [&_select]:border [&_select]:border-[#dbe8f0] [&_select]:bg-[#f8fbfd] [&_select]:px-3 [&_select]:py-2 [&_select]:text-xs [&_select]:font-semibold [&_select]:text-[#1e416a]">{children}</span></label>;
}

function PortCard({ name, draft, rate, wait, charge }: { name: string; draft: string; rate: string; wait: string; charge: string }) {
  return <div className="mt-3 flex gap-3"><span className="grid h-24 w-24 shrink-0 place-items-center rounded bg-[linear-gradient(145deg,#cce3ee,#49728c)] text-3xl">⚓</span><div className="flex-1 text-[10px]"><b className="text-[#24496f]">🇦🇺 {name}</b><dl className="mt-2 space-y-1 text-[#58708b]"><div className="flex justify-between"><dt>Max Draft</dt><dd>{draft}</dd></div><div className="flex justify-between"><dt>Loading Rate</dt><dd>{rate}</dd></div><div className="flex justify-between"><dt>Avg. Waiting Time</dt><dd>{wait}</dd></div><div className="flex justify-between"><dt>Port Charges (USD)</dt><dd>{charge}</dd></div><div className="flex justify-between"><dt>Tidal Restriction</dt><dd>Yes (1.2 – 1.8 m)</dd></div></dl></div></div>;
}

function Alternative({ title, vessel, rate, savings }: { title: string; vessel: string; rate: string; savings: string }) {
  return <div className="rounded-lg border border-[#e0ecf3] p-3"><p className="text-[10px] font-bold text-[#176fc0]">{title}</p><div className="mt-2 flex gap-2">{shipThumb('h-10 w-11')}<span className="flex-1"><b className="block text-xs text-[#365577]">{vessel}</b><b className="mt-1 block text-base text-[#173c6b]">{rate}</b><button className="mt-1 text-[10px] font-bold text-[#0873dc]" type="button">View Details →</button></span><small className="h-fit rounded bg-emerald-50 px-2 py-1 font-bold text-emerald-600">{savings}</small></div></div>;
}
