import { useMemo, useState } from 'react';

type Port = {
  id: string;
  name: string;
  state: string;
  capacity: string;
  throughput: string;
  utilization: string;
  turnaround: string;
  berths: string;
  draft: string;
  loa: string;
  beam: string;
  depth: string;
  status: 'Low' | 'Moderate' | 'High';
};

const ports: Port[] = [
  { id: 'paradip', name: 'Paradip', state: 'Odisha', capacity: '120 MTPA', throughput: '98 MTPA', utilization: '82%', turnaround: '2 – 3 days', berths: '11', draft: '18.5 m', loa: '300 m', beam: '50 m', depth: '19.0 m', status: 'Moderate' },
  { id: 'vizag', name: 'Vizag', state: 'Andhra Pradesh', capacity: '95 MTPA', throughput: '76 MTPA', utilization: '80%', turnaround: '2 – 3 days', berths: '10', draft: '16.5 m', loa: '290 m', beam: '48 m', depth: '17.0 m', status: 'Low' },
  { id: 'gangavaram', name: 'Gangavaram', state: 'Andhra Pradesh', capacity: '70 MTPA', throughput: '58 MTPA', utilization: '83%', turnaround: '1 – 2 days', berths: '9', draft: '21.0 m', loa: '320 m', beam: '52 m', depth: '21.0 m', status: 'Low' },
  { id: 'gopalpur', name: 'Gopalpur', state: 'Odisha', capacity: '55 MTPA', throughput: '42 MTPA', utilization: '76%', turnaround: '2 – 3 days', berths: '5', draft: '14.5 m', loa: '270 m', beam: '44 m', depth: '15.0 m', status: 'Moderate' },
  { id: 'dhamra', name: 'Dhamra', state: 'Odisha', capacity: '75 MTPA', throughput: '60 MTPA', utilization: '80%', turnaround: '1 – 2 days', berths: '6', draft: '18.0 m', loa: '310 m', beam: '50 m', depth: '18.5 m', status: 'Low' },
  { id: 'haldia', name: 'Haldia', state: 'West Bengal', capacity: '50 MTPA', throughput: '39 MTPA', utilization: '78%', turnaround: '3 – 4 days', berths: '8', draft: '8.5 m', loa: '220 m', beam: '36 m', depth: '9.0 m', status: 'High' },
  { id: 'sagar', name: 'Sagar', state: 'West Bengal', capacity: '42 MTPA', throughput: '31 MTPA', utilization: '74%', turnaround: '3 – 4 days', berths: '4', draft: '10.5 m', loa: '240 m', beam: '40 m', depth: '11.0 m', status: 'Moderate' },
];

const specifications = (port: Port) => [
  ['⚓', 'Max Draft', port.draft], ['♜', 'Max LOA', port.loa], ['▤', 'Max Beam', port.beam], ['▥', 'Channel Depth', port.depth], ['▣', 'Turning Basin', '600 m'], ['▦', 'Tidal Range', '1.2 – 1.8 m'], ['⚠', 'Pilotage', 'Compulsory'], ['◴', 'Operation', '24 / 7'], ['♧', 'Port Authority', `${port.name} Port Authority`],
];

export function PortsPage() {
  const [selectedId, setSelectedId] = useState('paradip');
  const [activeTab, setActiveTab] = useState('Port Overview');
  const [watchlist, setWatchlist] = useState<string[]>([]);
  const [compareVisible, setCompareVisible] = useState(false);
  const selected = useMemo(() => ports.find((port) => port.id === selectedId) ?? ports[0], [selectedId]);
  const isWatching = watchlist.includes(selected.id);

  return <section className="space-y-3 text-[#17345d]">
    <div className="flex flex-col justify-between gap-4 xl:flex-row xl:items-end"><div><p className="text-[11px] font-bold tracking-[.25em] text-[#617a96]">PORT INTELLIGENCE</p><h1 className="mt-1 text-3xl font-extrabold tracking-tight text-[#12396e] sm:text-4xl">Port Insights for Smarter Decisions</h1><p className="mt-1 text-base text-[#55708e]">Real-time port data, congestion status, vessel compatibility and operational insights for India’s East Coast.</p></div><div className="flex gap-3"><span className="hidden rounded-md border border-[#dbe8f0] bg-white px-4 py-3 text-xs font-semibold text-[#46617f] shadow-sm sm:block">12 Sep 2026, 14:32 (IST) &nbsp; <b className="text-emerald-600">● Live Data</b></span><button className="rounded-md bg-[#0873dc] px-5 py-3 text-xs font-bold text-white shadow-sm hover:bg-[#0560b7]" onClick={() => setCompareVisible((visible) => !visible)} type="button">☆ Compare Ports</button></div></div>
    {compareVisible ? <div className="rounded-lg border border-[#cfe3f0] bg-[#f5fbff] px-4 py-3 text-sm text-[#46627f]"><b className="text-[#173d6d]">Port comparison placeholder:</b> select additional ports when the live port-data backend is connected.</div> : null}
    <div className="flex gap-2 overflow-x-auto rounded-xl border border-[#dceaf2] bg-white p-1.5 shadow-sm">{ports.map((port) => <button className={`flex min-w-37.5 items-center gap-2 rounded-lg px-2 py-2 text-left transition ${port.id === selected.id ? 'border border-[#0a7bdf] bg-[#eef8ff] shadow-sm' : 'hover:bg-[#f6fbff]'}`} key={port.id} onClick={() => { setSelectedId(port.id); setActiveTab('Port Overview'); }} type="button"><PortVisual size="h-13 w-17" /><span><b className="block text-xs text-[#1f426d]">{port.name}</b><small className="mt-1 block text-[10px] text-[#617a93]">{port.state}</small></span></button>)}</div>
    <div className="grid gap-3 xl:grid-cols-[minmax(0,1fr)_380px]">
      <div className="space-y-3"><article className="rounded-xl border border-[#dceaf2] bg-white p-4 shadow-sm"><div className="flex flex-col gap-4 lg:flex-row"><PortVisual size="h-27 w-47" /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-extrabold text-[#153a70]">{selected.name} Port</h2><p className="mt-1 text-xs text-[#506c88]">⌖ {selected.state}, India &nbsp; | &nbsp; 20.3167° N, 86.6167° E</p><p className="mt-3 max-w-xl text-xs leading-5 text-[#4d6784]">Major port on the east coast, handling thermal coal, iron ore, containers and multiple bulk commodities. Strategically important for eastern and central India.</p></div><div className="flex gap-2"><button className={`rounded-md border px-3 py-2 text-xs font-bold ${isWatching ? 'border-amber-200 bg-amber-50 text-amber-700' : 'border-[#d6e6f1] bg-[#f6fbff] text-[#1373c7]'}`} onClick={() => setWatchlist((list) => list.includes(selected.id) ? list.filter((id) => id !== selected.id) : [...list, selected.id])} type="button">☆ {isWatching ? 'Watching' : 'Add to Watchlist'}</button><span className="rounded-md bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-700">● Operational</span></div></div></div></div><div className="mt-3 grid gap-2 sm:grid-cols-5"><Kpi icon="♜" value={selected.capacity} label="Total Capacity" /><Kpi icon="♜" value={selected.throughput} label="Current Throughput" /><Kpi icon="◔" value={selected.utilization} label="Capacity Utilization" /><Kpi icon="◴" value={selected.turnaround} label="Avg. Turnaround Time" /><Kpi icon="♜" value={selected.berths} label="Berths" /></div></article><div className="flex overflow-x-auto rounded-xl border border-[#dceaf2] bg-white p-1 shadow-sm">{['Port Overview', 'Berth Details', 'Vessel Compatibility', 'Cargo Handling', 'Port Fees', 'Performance', 'Notices'].map((tab) => <button className={`shrink-0 rounded-md px-3 py-3 text-[11px] font-bold ${activeTab === tab ? 'bg-[#eaf6ff] text-[#0d73cb]' : 'text-[#607991] hover:bg-[#f5faff]'}`} key={tab} onClick={() => setActiveTab(tab)} type="button">{tab}</button>)}</div></div>
      <article className="rounded-xl border border-[#dceaf2] bg-white p-3 shadow-sm"><h2 className="text-base font-extrabold text-[#153a70]">Live Port Camera</h2><div className="relative mt-3 grid h-48 place-items-center overflow-hidden rounded-lg bg-[linear-gradient(145deg,#92bbcf,#4f7287_50%,#1c405e)]"><div className="absolute inset-0 opacity-30" style={{ backgroundImage: 'linear-gradient(rgba(255,255,255,.35) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.35) 1px,transparent 1px)', backgroundSize: '30px 30px' }} /><span className="z-10 text-6xl drop-shadow-lg">⚓</span><span className="absolute right-3 top-3 rounded bg-white/90 px-2 py-1 text-[10px] font-bold text-emerald-700">● Live</span><span className="absolute bottom-3 left-3 rounded bg-slate-950/60 px-3 py-2 text-xs text-white">{selected.name} Port – Berth View</span><span className="absolute right-3 top-1/2 text-xl text-white">›</span><span className="absolute left-3 top-1/2 text-xl text-white">‹</span></div><p className="mt-2 text-[10px] text-[#6d849b]">Camera feed placeholder · connect an approved port camera/AIS provider.</p></article>
    </div>
    <div className="grid gap-3 xl:grid-cols-[1fr_1fr_1.2fr]">
      <article className="rounded-xl border border-[#dceaf2] bg-white p-3 shadow-sm"><h2 className="text-base font-extrabold text-[#153a70]">Key Specifications</h2><dl className="mt-2 divide-y divide-[#e8f0f4] text-xs">{specifications(selected).map(([icon, label, value]) => <div className="grid grid-cols-[20px_1.1fr_.9fr] py-1.5" key={label}><dt className="text-[#1574c5]">{icon}</dt><dt className="text-[#4e6885]">{label}</dt><dd className="font-semibold text-[#365374]">{value}</dd></div>)}</dl></article>
      <article className="rounded-xl border border-[#dceaf2] bg-white p-3 shadow-sm"><div className="flex justify-between"><h2 className="text-base font-extrabold text-[#153a70]">Live Port Status</h2><small className="text-[10px] text-[#73899d]">Last updated: 12 Sep 2026, 14:32 IST</small></div><dl className="mt-2 divide-y divide-[#e8f0f4] text-xs">{[['⚠', 'Congestion Level', selected.status], ['◴', 'Waiting Time', selected.turnaround], ['⚓', 'Anchored Vessels', '14'], ['♜', 'Vessels in Queue', '6'], ['▦', 'Berth Occupancy', selected.utilization], ['☼', 'Weather', 'Clear (28°C)'], ['♧', 'Wind Speed', '12 knots (NE)'], ['◉', 'Visibility', 'Good (> 10 km)']].map(([icon, label, value]) => <div className="grid grid-cols-[20px_1fr_auto] py-2" key={label}><dt className="text-[#1574c5]">{icon}</dt><dt className="text-[#4e6885]">{label}</dt><dd className={`font-bold ${value === 'Moderate' ? 'text-amber-600' : value === 'Low' || value === 'Good (> 10 km)' ? 'text-emerald-600' : 'text-[#365374]'}`}>{value}</dd></div>)}</dl></article>
      <article className="rounded-xl border border-[#dceaf2] bg-white p-3 shadow-sm"><h2 className="text-base font-extrabold text-[#153a70]">Vessel Size Distribution <span className="text-xs font-normal text-slate-500">(Last 30 Days)</span></h2><div className="mt-3 flex items-center gap-5"><Donut /><div className="space-y-2 text-[11px] text-[#4e6885]">{[['bg-[#1479d6]', 'Panamax', '38%'], ['bg-[#d0a63a]', 'Supramax', '26%'], ['bg-[#26ad78]', 'Handysize', '18%'], ['bg-[#8458dc]', 'Capesize', '12%'], ['bg-[#9eb2c7]', 'Others', '6%']].map(([color, type, percent]) => <p key={type}><i className={`mr-2 inline-block h-2 w-2 rounded-full ${color}`} />{type}<b className="ml-8">{percent}</b></p>)}</div></div><h3 className="mt-4 text-sm font-extrabold text-[#153a70]">Cargo Handling <span className="font-normal text-slate-500">(Last 30 Days)</span></h3><div className="mt-2 space-y-2">{[['Thermal Coal', '42%', 'bg-[#1689e2]'], ['Iron Ore', '28%', 'bg-orange-400'], ['Containers', '12%', 'bg-emerald-500'], ['Fertilizer', '8%', 'bg-violet-500'], ['Others', '10%', 'bg-slate-400']].map(([label, value, color]) => <div className="grid grid-cols-[90px_1fr_30px] items-center gap-2 text-[10px]" key={label}><span className="text-[#506a86]">{label}</span><i className="h-2 overflow-hidden rounded bg-[#eef3f6]"><i className={`block h-full rounded ${color}`} style={{ width: value }} /></i><b className="text-[#526b87]">{value}</b></div>)}</div></article>
    </div>
    <div className="grid gap-3 xl:grid-cols-[1.2fr_1fr_1fr]"><TrendChart /><TurnaroundChart /><article className="rounded-xl border border-[#dceaf2] bg-white p-3 shadow-sm"><div className="flex justify-between"><h2 className="text-base font-extrabold text-[#153a70]">Important Notices</h2><button className="text-xs font-bold text-[#0f75cb]" type="button">View All →</button></div><div className="mt-3 divide-y divide-[#e8f0f4]">{[['bg-rose-100 text-rose-600', 'Notice', 'Berth 6 maintenance scheduled (15–17 Sep 2026)', '11 Sep 2026'], ['bg-amber-100 text-amber-700', 'Advisory', 'Increased vessel traffic expected next week', '10 Sep 2026'], ['bg-blue-100 text-blue-700', 'Update', 'Channel depth restored to 19.0 m', '09 Sep 2026'], ['bg-emerald-100 text-emerald-700', 'Info', 'New coal handling system operational', '08 Sep 2026']].map(([style, type, notice, date]) => <div className="grid grid-cols-[58px_1fr_70px] gap-2 py-3 text-[10px]" key={notice}><span className={`h-fit rounded px-2 py-1 text-center font-bold ${style}`}>{type}</span><span className="text-[#4e6885]">{notice}</span><time className="text-right text-slate-400">{date}</time></div>)}</div></article></div>
  </section>;
}

function PortVisual({ size }: { size: string }) { return <span className={`grid shrink-0 ${size} place-items-center rounded bg-[linear-gradient(145deg,#d9ad8c,#557389_50%,#203f5a)] text-3xl shadow-inner`}>⚓</span>; }
function Kpi({ icon, value, label }: { icon: string; value: string; label: string }) { return <div className="flex items-center gap-3 rounded-lg border border-[#e4edf3] p-3"><span className="text-xl text-[#1479d6]">{icon}</span><span><b className="block text-sm text-[#24496f]">{value}</b><small className="text-[10px] text-[#637c94]">{label}</small></span></div>; }
function Donut() { return <div className="grid h-31 w-31 place-items-center rounded-full" style={{ background: 'conic-gradient(#1479d6 0 38%,#d0a63a 38% 64%,#26ad78 64% 82%,#8458dc 82% 94%,#9eb2c7 94% 100%)' }}><div className="grid h-17 w-17 place-items-center rounded-full bg-white text-center"><b className="text-lg text-[#173b70]">213</b><small className="-mt-1 text-[9px] text-slate-500">Vessels</small></div></div>; }
function TrendChart() { return <article className="rounded-xl border border-[#dceaf2] bg-white p-3 shadow-sm"><div className="flex justify-between"><div><h2 className="text-base font-extrabold text-[#153a70]">Throughput Trend</h2><p className="text-[10px] text-[#617b94]">Million Tonnes</p></div><span className="text-[10px] font-semibold text-[#53708d]">— 2025 &nbsp; <b className="text-[#1479d6]">— 2026</b></span></div><svg aria-label="Port throughput trend placeholder" className="mt-2 h-30 w-full" viewBox="0 0 440 130" preserveAspectRatio="none"><g stroke="#e4edf3">{[20,45,70,95,120].map((y) => <line key={y} x1="25" x2="430" y1={y} y2={y} />)}</g><path d="M25 88 L62 87 L99 79 L136 82 L173 75 L210 77 L247 83 L284 70 L321 79 L358 73 L395 58 L430 55" fill="none" stroke="#1479d6" strokeWidth="3" /><path d="M25 99 L62 96 L99 93 L136 90 L173 92 L210 87 L247 94 L284 86 L321 91 L358 83 L395 77 L430 73" fill="none" stroke="#a9c9ec" strokeWidth="3" />{['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'].map((month,index) => <text fill="#71879c" fontSize="9" key={month} x={25 + index * 37} y="129">{month}</text>)}</svg></article>; }
function TurnaroundChart() { const values = [1.8,2.1,2.4,2.7,2.2,2.0,2.3,2.6,2.4]; return <article className="rounded-xl border border-[#dceaf2] bg-white p-3 shadow-sm"><h2 className="text-base font-extrabold text-[#153a70]">Average Turnaround Time (Days)</h2><div className="mt-4 flex h-28 items-end justify-around border-b border-[#e2ebf1] px-3">{values.map((value, index) => <div className="flex h-full w-7 flex-col items-center justify-end" key={`${value}-${index}`}><b className="mb-1 text-[9px] text-[#46617e]">{value}</b><i className="w-4 rounded-t bg-[#54a5e6]" style={{ height: `${value / 3 * 88}px` }} /></div>)}</div><div className="mt-2 flex justify-around text-[9px] text-[#71879c]">{['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep'].map((month) => <span key={month}>{month}</span>)}</div></article>; }
